[package]
name = "cowproof-report"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cowproof-report"
path = "src/main.rs"

[dependencies]
anyhow = "1"
cowproof-prove = { version = "0.1.0", path = "../cowproof-prove" }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
cowproof-core = { version = "0.1.0", path = "../cowproof-core" }
